### ISSUE TITLE
1.9.1 version for mpy-cross-pycom?

### ISSUE THREAD

**Issue by jdeltoft** [robert-hh/Shared-Stuff#1]
Hi,
   I am using your exe for windows for cross compiling for nodemcu.  Thank you!   I just updated to 1.9.1 and noticed the mpy files are now incompatible.  Would you mind rebuilding for the latest firmware?  Thanks in advance if you can!

Justin

**Comment by robert-hh** [comment]
mpy-cross.exe should be compatible for v1.9.1 / Micropython.org. But I can rebuild that now, just to be sure.

**Comment by jdeltoft** [comment]
Do you think that will work with nodeMCU?  I tried mpy-cross.exe and mpy-cross-pycom.exe and only the pycom worked for me.

**Comment by robert-hh** [comment]
mpy-cross.exe is the version maintained for the micropython.org build. And if you load an v1.9.1 from the micropython.org site to you nodemcu, that should work. mpy-cross-pycom .exe is the build for the pycom.io versions, that should have worked up to micropython.org v1.8.7. I cannot remeber exactly when these two lines diverted with respect to mpy-cross.

**Comment by jdeltoft** [comment]
ahh!  Ok.  Yes, I must have stumbled on the pycom version working with the 1.8.7 version even though it was wrong, which may explain my original issues!  Sorry for the confusion.  I just tried the latest 1.9.1 mpy-cross.exe and it's all good for me.  Thank you!!!  I really appreciate you building this.  I may try using docker to build these in the future.  Will let you know if it works, but right now you're allowing me to be lazy.  :-)
