### ISSUE TITLE
help to create firmware and esp bin

### ISSUE THREAD

**Issue by thbeh** [robert-hh/Shared-Stuff#2]
Hi, not an issue here but if I could get your help to show me your steps to create both the firmware*.bin and esp*.bin files as I would like to add some additional module to them. Thanks in advance.

**Comment by robert-hh** [comment]
I just followed the instructions here: https://github.com/micropython/micropython/tree/master/ports/esp8266 and the one this file point at. I use a debian 9 (Linux) system. Other Linux variants like Ubuntu should be fine. Windows or OS X computers may not work. The build process creates both files.
The firmware-combined.bin file is equivalent to what can be downloaded from the micropython download page.
Addtional Python modules have to be placed in the modules subdirectory. If the binary gets too large, you may drop some of the built-in modules. A good candidate is btree. There is a flag for btree on/off in Makefile.
