### ISSUE TITLE
wm_w600_FAT_threading.fls

### ISSUE THREAD

**Issue by caochangli123** [robert-hh/Shared-Stuff#4]
About this firmware, how can I get the password information after using the ‘oneshot’ function？

**Comment by robert-hh** [comment]
I do not know. This is a Winnermicro feature, and the WinnerMicro documentation does not tell it. Maybe you raise your question in the Winnermicro Git repository at https://github.com/WinnerMicro/micropython

**Comment by caochangli123** [comment]
> I do not know. This is a Winnermicro feature, and the WinnerMicro documentation does not tell it. Maybe you raise your question in the Winnermicro Git repository at https://github.com/WinnerMicro/micropython

OK
