### ISSUE TITLE
Generic Esp32

### ISSUE THREAD

**Issue by Tbruno25** [robert-hh/Shared-Stuff#5]
I came across an old forum thread on pycom where you explained how to get pycom firmware working on a generic esp32. It looks like the wipy.bin file you referenced is no longer part of this repo -- just wondering if there's another way? 

Thanks in advance!

**Comment by robert-hh** [comment]
I have rebuilt install packages for generic ESP32 devices. 

ESP32-4MB-1.20.2.rc11.tar.gz and ESP32-8MB-1.20.2.rc11.tar.gz

The difference is the flash size. If SPIRAM is present, it will be used. They work with ESP32 Rev1, ESP32 Rev 0 and ESP32 Pico D4 chips.

You can use the Pycom Firmware installer for uploading. For boards with the espressif bootloader switch mechanism (almost all boards except the Pycom ones), use the option -r of the command line updater. You may as well use the updater.py script from the pycom repository at https://github.com/pycom/pycom-micropython-sigfox/tree/Dev/esp32/tools/fw_updater. Call `python3 updater.py --help` for usage. It is identical to the pycom cli updater.

**Comment by Tbruno25** [comment]
I have been trying to find a way to use CAN with esp32 and micropython for a while and this seems to fit the bill. Thank you very much, Robert -- you rock!

**Comment by Tbruno25** [comment]
@robert-hh CAN works perfect, I am pretty stoked! One last favor -- is there any chance you could compile utilizing [this pins.csv](https://raw.githubusercontent.com/pacmac/micropython-share/master/wipy-wroom/pins.csv) file instead? This will allow easier pin configuration on the esp32-wroom-32. I tried myself using wipy firmware but had no luck once I flashed it to the board.

**Comment by robert-hh** [comment]
I can try that. Some notes. I omitted GPIO16 and GPIO17, because they are used by the PICO-D4 devices. And you do not have to us the "Pxx" numbers. You can use "GPIOxx" or "GPIxx" for the  input only pins.

**Comment by Tbruno25** [comment]
@robert-hh Oh, awesome. Then don't even bother re compiling -- the GPIO syntax is fine. I just did not want to have to create a converter function. Thanks again!
