### ISSUE TITLE
No REPL After Flash

### ISSUE THREAD

**Issue by moefear85** [robert-hh/Shared-Stuff#6]
Hello,

Are you sure the image is working?
This is all I see after boot:

ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x1 (POWERON),boot:0xa (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x12f8
load:0x4004c000,len:0x8c4
load:0x40050000,len:0x2ca4
entry 0x4004c1a8

And then it just stops there. I try to type, but nothing happens. There's no REPL. Is the REPL perhaps on non-standard Serial Pins, zB TX1/RX1 or TX2/RX2, or is it maybe over USB-CDC? I don't have a way to try that yet.

Thx

**Comment by robert-hh** [comment]
I made that image for another board member. I cannot recall if that worked. I do not have a generic S2 board, just an Adafruit S2 board. It should have a REPL prompt at the USB serial channel.

**Comment by moefear85** [comment]
in case anyone is wondering, I didn't know the repl has been moved over to USB-CDC. It works perfectly when connected as a usb device.
