### ISSUE TITLE
error when creating a 2nd thread on wm_w600_lfs_threading.fls

### ISSUE THREAD

**Issue by tatalor85** [robert-hh/Shared-Stuff#7]
Hello,

I'm running this code on W600 with 1.20 image with threading:

import _thread
import time

def th_func(delay, id):
    while True:
        time.sleep(delay)
        print('Running thread %d' % id)

for i in range(2):
    _thread.start_new_thread(th_func, (i + 1, i))

Only one thread is created. For the 2nd call, I get:

  File "main.py", line 12, in <module>
OSError: can't create thread

Same error was on 1.19.

Thanks!

PS: the same code runs ok on esp32c3 board with uPython 1.20, so maybe it's an error in the w600 build.

**Comment by robert-hh** [comment]
It's a stack size limit. It is limited to 4096 stack items (32 bit integers), which is the default size. You can reduce it with _thread.stack_size(n). If you set it to 2048, you can run two threads, with 1024 it's four. With 1024, it's still 4 kByte.

**Comment by tatalor85** [comment]
I set it to 1024, but I can create only two threads with the code above.

**Comment by robert-hh** [comment]
Looking into the code (I wrote): The smallest size one can set is 2k. But I just changed the thread's stack allocation scheme, allowing more threads to be created.  The binary is updated.

**Comment by tatalor85** [comment]
seen 14 threads  now, thanks!
